### ISSUE TITLE
Errors in example in Chaper 1

### ISSUE THREAD

**Issue by fryguybob** [sdiehl/write-you-a-haskell#1]
The data types given for the example abstract syntax:
```{.haskell}
type Name = String

data Expr
  = Var Name
  | Lit Name
  | Op PrimOp [Expr]
  | Let Name [Name] Expr

data Lit 
  = LitInt Int
```
does not match the value given later:
```{.haskell}
Let "f" ["x"] (Op Add [Var "x", Lit (LitInt 1)])
```
Specifically `Lit (LitInt 1)`.

**Comment by dan-t** [comment]
Yes, it should most likely be:

    type Name = String
    
    data Expr
      = Var Name
      | Lit Lit
      | Op PrimOp [Expr]
      | Let Name [Name] Expr
    
    data Lit 
      = LitInt Int

    data PrimOp
      = Add

Perhaps it's a good idea to name the second `Lit` just `Literal`, otherwise the two `Lit` might look a bit strange.

Great work Stephen! :)

**Comment by sdiehl** [comment]
Thanks for catching this guys.
