### ISSUE TITLE
Ebook & AZW3 (for kindle) versions of PDF

### ISSUE THREAD

**Issue by Cmdv** [sdiehl/write-you-a-haskell#100]
Hi, I've just manually converted the pdf into Ebook + AZW3 formats.

It's not using the script but there seemed to be interest to these formats so wondered if I should make adjustments to the menu and add 2 extra links? 
but I assume you wouldn't want the file living on the repo as they are about 3mb in total! 🤔

Here is a zip of them both

edit: the Epub version was the wrong one! (reuploaded)

[Write you a haskell Ebook AZW3.zip](https://github.com/sdiehl/write-you-a-haskell/files/2187743/Write.you.a.haskell.Ebook.AZW3.zip)

**Comment by sdiehl** [comment]
Wonderful, I'll add these to the website and host them there.

**Comment by Cmdv** [comment]
Not a problem, I'll close this issue now 😄 

Also here is the `.pages` file if you ever need to do edits to the original.

[Write-You-a-Haskell.pages.zip](https://github.com/sdiehl/write-you-a-haskell/files/2187494/Write-You-a-Haskell.pages.zip)

**Comment by Cmdv** [comment]
Just got pointed out to me the Epub version was incorrect, just did another upload on original comment!
