### ISSUE TITLE
Unification fail in type checker

### ISSUE THREAD

**Issue by Abhiroop** [sdiehl/write-you-a-haskell#107]
When attempting to run the type checker on the example given in the repo with factorial, I run into a typechecker error:
```
Poly> let fact = fix (\fact -> \n -> if (n == 0) then 1 else  ( n * ( fact (n-1) ) )    )
Cannot unify types:
	Int
with
	Int -> d
```
According to the book this should spit out the correct type.

**Comment by simonvpe** [comment]
I'm getting the same error on chapter 7, you closed this @Abhiroop - did you find an answer?
