### ISSUE TITLE
Confused about "Applicatives are strictly less general than monads."

### ISSUE THREAD

**Issue by ethercrow** [sdiehl/write-you-a-haskell#12]
I've only recently learned sufficiently not-hand-wavy meaning of the word "powerful", which is if X is more powerful than Y then you can do some things with X that are not possible with Y.

However, it looks like I don't yet understand the meaning of the word "general". I would guess that "Applicatives are strictly less general than monads" means that there are more monads out there than applicatives, but the opposite is the case. Could you clarify?

**Comment by sdiehl** [comment]
Should probably be more along the lines of "less powerful" or "less expressive". Every monad does arise out an applicative in theory. 

I'll think how to rephrase this, open to any suggestions.

**Comment by igstan** [comment]
FWIW, Simon Marlow says "... Monad is more expressive than Applicative ..." in this [Haskel Cast episode][0], at 11:05.

[0]: http://www.haskellcast.com/episode/004-simon-marlow-on-parallelism-and-concurrency/

**Comment by reinh** [comment]
@igstan I am going to claim credit for this one then. ;) :+1:
