### ISSUE TITLE
Usage or 'reified' in Evaluation

### ISSUE THREAD

**Issue by NicolasT** [sdiehl/write-you-a-haskell#20]
The Evaluation chapter says

```
This value will be passed off to Haskell and reified into real world effects.
```

I believe this is somewhat confusing. In my understanding, that value is not reified into real world effects. On the contrary, it is a reification of real world effects, which can then be interpreted to actually cause those effects.
Or am I misunderstanding the concept of reification?

**Comment by sdiehl** [comment]
I mean to say it is lifted into the main function of Haskell and evaluated. Perhaps that isn't clear from the text?
