### ISSUE TITLE
Can't build with base >= 4.7

### ISSUE THREAD

**Issue by dlight** [sdiehl/write-you-a-haskell#32]
Perhaps I'm doing something dumb, but I can't build any of the code (here is chapter7/poly but others don't build as well)

    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.8.4
    $ cabal --version
    cabal-install version 1.22.0.0
    using version 1.22.0.0 of the Cabal library 
    $ cabal install
    Resolving dependencies...
    cabal: Could not resolve dependencies:
    trying: poly-0.1.0.0 (user goal)
    next goal: base (dependency of poly-0.1.0.0)
    rejecting: base-4.7.0.2/installed-bfd... (conflict: poly => base>=4.6 && <4.7)
    rejecting: base-4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0, 4.5.1.0, 4.5.0.0,
    4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1, 4.2.0.0, 4.1.0.0,
    4.0.0.0, 3.0.3.2, 3.0.3.1 (global constraint requires installed instance)
    Dependency tree exhaustively searched.
    
    Note: when using a sandbox, all packages are required to have consistent
    dependencies. Try reinstalling/unregistering the offending packages or
    recreating the sandbox.

Is there a greater reason for not supporting GHC 7.8?

**Comment by dlight** [comment]
Actually it seems it's because repline doesn't support base 4.7.

**Comment by sdiehl** [comment]
I bumped the upper bound on ``repline`` and reuploaded to hackage. Let me know if that fixes your problem.

https://hackage.haskell.org/package/repline-0.1.3.0

**Comment by dlight** [comment]
Thank you. By also changing the bounds of the packages here they run fine.

**Comment by sdiehl** [comment]
Great. Thanks for reporting.
