### ISSUE TITLE
poly: trouble with "it"

### ISSUE THREAD

**Issue by chsievers** [sdiehl/write-you-a-haskell#39]
I'm not sure  if `it` is a feature or an implementation artefact, but the user can find it with `:browse` and using it leads to trouble:

``` haskell
Poly> 1
1 : Int
Poly> :browse
it : Int
Poly> it+it
4 : Int
Poly> it==it
poly: Pattern match failure in do expression at Eval.hs:39:5-11
```

**Comment by sdiehl** [comment]
I'll be out for a few days, but I'l look at this weekend. I think it's just a silly bug, trying to replicate GHCi's ``it`` variable which holds the last evaluated expression.
