### ISSUE TITLE
Small error in Parsing section

### ISSUE THREAD

**Issue by rafalio** [sdiehl/write-you-a-haskell#4]
In the Parsing section, http://dev.stephendiehl.com/fun/parsers.html, you write "Recall that in Haskell in the String type is itself defined to be a list of Char values...", but you write it as a list of String values. That section should have single quotes instead:

    "1+2*3"
    ['1','+', '2', '*', '3']

**Comment by sdiehl** [comment]
You are correct, it should be a list of chars.
