### ISSUE TITLE
Untyped chapter has out of order material

### ISSUE THREAD

**Issue by reinh** [sdiehl/write-you-a-haskell#8]
Stephen, wonderful work here!

The Untyped chapter includes a section on pretty printing but some of the material relating to pretty printing appears earlier, at the end of the [Reduction](http://dev.stephendiehl.com/fun/lambda_calculus.html#reduction) section, and seems out of order.

**Comment by sdiehl** [comment]
Indeed, the pretty printer section wasn't moved properly.

**Comment by sdiehl** [comment]
I reflowed the section on the Untyped Lambda Calculus, hopefully it makes more sense now.

https://github.com/sdiehl/write-you-a-haskell/blob/master/lambda_calculus.md

**Comment by reinh** [comment]
Unfortunately, now the antecedent for `p` in "The `p` variable" is "`class Pretty p where`" when it should be "`ppr p e = case e of`" below.
